version: '2'
services:
  grunt:
    build:
      context: ../../../
      dockerfile: ./config/docker/grunt/Dockerfile-grunt
    image: angular_moviemasher_grunt
    volumes:
      - "../../../Gruntfile.js:/data/Gruntfile.js"
      - "../../../bower.json:/data/bower.json"
      - "../../../package.json:/data/package.json"
      - "../../../dist:/data/dist"
      - "../../../src:/data/src"
      - "../../../app:/data/app"
      - "../../../bower_components:/data/bower_components"
