
FROM php:apache
MAINTAINER Movie Masher <support@moviemasher.com>

# install utilities needed by composer
RUN apt-get update && apt-get install -y git
RUN apt-get update && apt-get install -y zlib1g-dev && docker-php-ext-install zip

# install composer in /mnt directory
RUN cd /mnt ; curl -sS https://getcomposer.org/installer | php ;
