version: '2'
services:
  angular_moviemasher:
    image: moviemasher/angular-moviemasher:1.0.23
    container_name: angular_moviemasher
    build:
      context: ../../../
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "../../../log:/tmp/moviemasher/log/"
      - "../../../src:/var/www/html/angular-moviemasher/src"
      - "../moviemasher.ini:/var/www/config/moviemasher.ini"
      - "../../../app:/var/www/html/angular-moviemasher/app"
      - "../../../dist:/var/www/html/angular-moviemasher/dist"
      - "../../../node_modules:/var/www/html/angular-moviemasher/node_modules"
      - "../../../tmp/user-media:/var/www/html/user-media"
      - "../../../tmp/user-data:/var/www/user-data"
  moviemasher_rb:
    image: moviemasher/moviemasher.rb:4.0.25
    container_name: angular_moviemasher_rb
    volumes_from:
      - angular_moviemasher
    volumes:
      - "../../../tmp/error:/tmp/moviemasher/error"
      - "../../../tmp/render:/tmp/moviemasher/render"
      - "../../../tmp/download:/tmp/moviemasher/download"
      - "../../../tmp/log:/tmp/moviemasher/log"
      - "../../../../moviemasher.rb/:/mnt/moviemasher.rb"
    command: process_loop -v debug --render_save=1
    tty: true
